just to test the pr merged disablity till all checks pass

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -90,3 +90,11 @@ jobs:
             org.opencontainers.image.created=${{ steps.prep.outputs.created }}
             org.opencontainers.image.revision=${{ github.sha }}
             org.opencontainers.image.licenses=${{ fromJson(steps.repo.outputs.result).license.spdx_id }}
+      - 
+        name: Prevent PR merge
+        run: |
+          # Check if any previous step failed
+          if [[ ${{ job.status }} == 'failure' ]]; then
+            echo "Checks failed. The merge button will remain disabled."
+            exit 1
+          fi
